name: Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/cosmo-discord-bot:latest
                  build-args: |
                      DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
                      CLIENT_ID=${{ secrets.CLIENT_ID }}
                      DEVELOPER_IDS=${{ secrets.DEVELOPER_IDS }}
                      NODE_ENV=production

            - name: Pull image
              run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cosmo-discord-bot:latest

            - name: Deploy to EC2
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cosmo-discord-bot:latest
                      sudo docker stop discord-app || true
                      sudo docker rm discord-app || true
                      sudo docker run -d --name discord-app -p 3005:3000 \
                            -e DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} \
                            -e CLIENT_ID=${{ secrets.CLIENT_ID }} \
                            -e DEVELOPER_IDS=${{ secrets.DEVELOPER_IDS }} \
                            -e NODE_ENV=production \
                            ${{ secrets.DOCKERHUB_USERNAME }}/cosmo-discord-bot:latest
